name: Monthly Trigger

on:
  schedule:
    # Runs at 00:00 UTC on the 1st day of every month
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Download latest CC-CEDICT file
      run: wget https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz