name: Convert CC-CEDICT

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC on the 1st day of every month
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Download latest CC-CEDICT file
      run: wget https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz
    - name: Extract file
      uses: ihiroky/extract-action@v1
      with:
        file_path: cedict_1_0_ts_utf-8_mdbg.txt.gz
        extract_dir: .
    - name: Convert CC-CEDICT into Yomitan format
      run: python main.py cedict_1_0_ts_utf-8_mdbg.txt --output-directory /release
    - name: Convert CC-CEDICT into Yomitan format (Bullets)
      run: python main.py cedict_1_0_ts_utf-8_mdbg.txt --output-directory /release --separate
    - name: Convert CC-CEDICT into Yomitan format (Numbered Pinyin)
      run: python main.py cedict_1_0_ts_utf-8_mdbg.txt --output-directory /release --pinyin-numbers
    - name: Convert CC-CEDICT into Yomitan format (Bullets + Numbered Pinyin)
      run: python main.py cedict_1_0_ts_utf-8_mdbg.txt --output-directory /release --separate --pinyin-numbers
    
